### ISSUE TITLE
[Feature Request] Make hidden breakpoints match tailwind breakpoints

### ISSUE THREAD

**Issue by nxy7** [svelteuidev/svelteui#108]
### Usage example, including component, action, motion, or utility API

Hello, I suggest setting hidden breakpoints to match tailwind (and windi) breakpoints. This would result in more familiar api. So instead of
```
breakpoints: {
        xs: 576,
        sm: 768,
        md: 992,
        lg: 1200,
        xl: 1400
    }
```
maybe it would be worth having
``` 
breakpoints: {
      'sm': '640px',
      'md': '768px',
      'lg': '1024px',
      'xl': '1280px',
      '2xl': '1536px',
}
```
Alternatively it would be nice if we could set breakpoints px values.

### Possible implementation - describe how the feature can be implemented

Simple change of values, super easy, barely an inconvenience.

### Do you want to contribute this feature and create a pull request

Yes

**Comment by Brisklemonade** [comment]
I'm open to the idea of extending the breakpoint's to include Tailwind's. I don't want to remove the ones currently implemented though.

```ts
breakpoints: {
      …previous_breakpoints
      'smTW': '640px',
      'mdTW': '768px',
      'lgTW': '1024px',
      'xlTW': '1280px',
      '2xlTW': '1536px',
}
```

**Comment by nxy7** [comment]
If you think it won't be confusing then it might be good compromise.

**Comment by Brisklemonade** [comment]
Actually I think a better alternative would be adding those through your own config. Currently that isn't possible, but it will be soon.
