### ISSUE TITLE
Popper is broken

### ISSUE THREAD

**Issue by LukasDoesDev** [svelteuidev/svelteui#117]
### What package has an issue

@svelteuidev/core

### A clear and concise description of what the bug is

`Uncaught (in promise) TypeError: X.arrow is undefined` error from Popper.svelte

### In which browser(s) did the problem occur?

Firefox

### Steps To Reproduce

1. Copy code from https://github.com/svelteuidev/svelteui/blob/main/packages/svelteui-demos/src/lib/demos/core/AppShell/_HeadContent.svelte#L31-L37=
2. Remove the `use={[[hotkey, ...` prop
3. Hover over the theme switcher

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

### Relevant Assets

Error in development mode:
![image](https://user-images.githubusercontent.com/51633285/173245663-b9850844-c705-4c89-9cda-8a0c0da3df20.png)
Error when built and optimized:
![image](https://user-images.githubusercontent.com/51633285/173245665-a5856e51-e11c-4358-927a-6c869eae22c7.png)

**Comment by Brisklemonade** [comment]
Issue fixed in PR (#118)
