### ISSUE TITLE
[Feature Request] update workflows to cache the npm install and package steps

### ISSUE THREAD

**Issue by Brisklemonade** [svelteuidev/svelteui#124]
### Usage example, including component, action, motion, or utility API

The workflow would work the exact same, the only additions would be caching the `npm install`, and `npm run package` steps; so that the workflows run faster.

### Possible implementation - describe how the feature can be implemented

Simply adding more steps to the jobs

### Do you want to contribute this feature and create a pull request

Yes

**Comment by BeeMargarida** [comment]
I can pick this up

**Comment by Brisklemonade** [comment]
completed in (#129)
