### ISSUE TITLE
Checkbox doesnt seem to have keyboard support

### ISSUE THREAD

**Issue by Suyashtnt** [svelteuidev/svelteui#127]
### What package has an issue

@svelteuidev/core

### A clear and concise description of what the bug is

I'm currently checking out the docs for SvelteUI and seeing how its keyboard nav works. When I try to press `enter` on the checkbox at https://www.svelteui.org/core/checkbox, it does nothing

### In which browser(s) did the problem occur?

Chrome, Other - list in description

### Steps To Reproduce

1. Go to https://www.svelteui.org/core/checkbox
2. press `tab` until the checkbox is selected
3. press `enter` on checkbox
4. realise it does nothing

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

No

### Relevant Assets

Other browser tested on was Brave

![image](https://user-images.githubusercontent.com/45307955/174617605-4cb7e143-c2c0-4ad4-bfd6-d038a7e09c9f.png)
Pressing enter does nothing

**Comment by Brisklemonade** [comment]
The issue title seems to be wrong. In terms of the checkbox, clicking the spacebar while it's focused gives you the effect you wanted.
