### ISSUE TITLE
[Feature Request] Modal/Dialog

### ISSUE THREAD

**Issue by Suyashtnt** [svelteuidev/svelteui#133]
### Usage example, including component, action, motion, or utility API

This is based of [headlessUI](https://svelte-headlessui.goss.io/docs/dialog#basic-example)

```svelte
<script>
  import {
    Dialog,
    DialogOverlay,
    DialogTitle,
    DialogDescription,
  } from "@svelteuidev/core";
  let isOpen = true;
</script>

<Dialog open={isOpen} on:close={() => (isOpen = false)}>
  <DialogOverlay />

  <DialogTitle>Deactivate account</DialogTitle>
  <DialogDescription>
    This will permanently deactivate your account
  </DialogDescription>

  <p>
    Are you sure you want to deactivate your account? All of your data will be
    permanently removed. This action cannot be undone.
  </p>

  <button on:click={() => (isOpen = false)}>Deactivate</button>
  <button on:click={() => (isOpen = false)}>Cancel</button>
</Dialog>

```

### Possible implementation - describe how the feature can be implemented

check out https://github.com/rgossiaux/svelte-headlessui/tree/master/src/lib/components/dialog

### Do you want to contribute this feature and create a pull request

No

**Comment by Brisklemonade** [comment]
We have made a Modal component, and it's coming in the next minor update!
