### ISSUE TITLE
Docs for Month component says "@mantine/dates"

### ISSUE THREAD

**Issue by JasonXu314** [svelteuidev/svelteui#151]
### Link to the page where something isn't quite right

https://www.svelteui.org/dates/month

### Exact quote of what is wrong

Docs say "All @mantine/dates components are built with [dayjs](https://day.js.org/) library", whereas they should probably say "All @svelteuidev/dates components are built with [dayjs](https://day.js.org/) library"

### Are you willing to create pull request with the fix?

Yes

**Comment by Brisklemonade** [comment]
Thank you for catching that!
