### ISSUE TITLE
Github and Discord button are broken

### ISSUE THREAD

**Issue by pilcrowOnPaper** [svelteuidev/svelteui#152]
### Link to the page where something isn't quite right

https://www.svelteui.org

### Exact quote of what is wrong

Browser: Safari (iPadOS 15.5), Safari (MacOS Monterey 12.4), Chrome v98 (MacOS Monterey 12.4)

Currently, the buttons are loaded as:
```html
<button href>[Github SVG]</button>
```

It should be fixed to:
```html
<a href="https://github.com/...">[Github SVG]</a>
```

### Are you willing to create pull request with the fix?

No

**Comment by BeeMargarida** [comment]
I can confirm this, if no one wants to pick this up I can fix it

**Comment by cananda** [comment]
Let me try fixing it

**Comment by Brisklemonade** [comment]
@cananda do you plan on fixing it within the next couple of days?

**Comment by Brisklemonade** [comment]
Fixed, sorry @cananda but I heard nothing back from you.
