### ISSUE TITLE
[Feature Request] Roadmap for contributing

### ISSUE THREAD

**Issue by emarforio** [svelteuidev/svelteui#154]
### Usage example, including component, action, motion, or utility API

As someone that just learned about this project I would like to offer my help and contribute to the codebase. However, there is no roadmap or list of planned features that should be implemented and in what order. I know things that *I* would like of course but I would like to know if they align with the project scope or just give a helping hand to otherwise stagnant issues.

It would also give others the insight to know what the core developers are currently working on and what is next on the list. This would also help to show how mature the project is, eg how much work is it until it is not in beta anymore?

### Possible implementation - describe how the feature can be implemented

Either a well populated issue list on GitHub or a simple checklist on the main README, CONTRIBUTORS or similar would be a viable solution.

### Do you want to contribute this feature and create a pull request

No

**Comment by emarforio** [comment]
I just found a roadmap in the wiki which is very nice but it seems abandoned/not updated.

**Comment by Brisklemonade** [comment]
I've started a Roadmap in the readme. There are some set items that will be added, but I would love community input and involvement. If you have any ideas I would love to discuss them!
