### ISSUE TITLE
[Feature Request] Support custom icons for MenuIcon component

### ISSUE THREAD

**Issue by smartgoo** [svelteuidev/svelteui#156]
### Usage example, including component, action, motion, or utility API

It looks like the icon rendered by the [MenuIcon component](https://github.com/svelteuidev/svelteui/blob/main/packages/svelteui-core/src/lib/components/Menu/MenuIcon.svelte) cannot be set to a custom icon. Unless I'm missing something, an SVG is passed to `ActionItem` component inside of `MenuIcon` with no way to override it. Snippet below is from [MenuIcon component](https://github.com/svelteuidev/svelteui/blob/main/packages/svelteui-core/src/lib/components/Menu/MenuIcon.svelte):

```svelte
<ActionIcon
	bind:element
	use={[forwardEvents, [useActions, $$restProps?.use]]}
	class={className}
	{...$$restProps}
>
	<svg
		width={size}
		height={size}
		viewBox="0 0 15 15"
		fill="none"
		xmlns="http://www.w3.org/2000/svg"
	>
		<path
			d="M3.625 7.5C3.625 8.12132 3.12132 8.625 2.5 8.625C1.87868 8.625 1.375 8.12132 1.375 7.5C1.375 6.87868 1.87868 6.375 2.5 6.375C3.12132 6.375 3.625 6.87868 3.625 7.5ZM8.625 7.5C8.625 8.12132 8.12132 8.625 7.5 8.625C6.87868 8.625 6.375 8.12132 6.375 7.5C6.375 6.87868 6.87868 6.375 7.5 6.375C8.12132 6.375 8.625 6.87868 8.625 7.5ZM12.5 8.625C13.1213 8.625 13.625 8.12132 13.625 7.5C13.625 6.87868 13.1213 6.375 12.5 6.375C11.8787 6.375 11.375 6.87868 11.375 7.5C11.375 8.12132 11.8787 8.625 12.5 8.625Z"
			fill="currentColor"
			fill-rule="evenodd"
			clip-rule="evenodd"
		/>
	</svg>
</ActionIcon>
```

It would be useful to allow the icon rendered by `MenuIcon` to be customized, while leaving the current SVG as the default. 

It would also be useful to allow this icon to be customized while using the `Menu` component.

### Possible implementation - describe how the feature can be implemented

For `MenuIcon`: expose a slot that the custom icon can be passed into.

For `Menu`: expose 2 named slots. One for the `MenuIcon` icon slot. The other for the current `Menu` slot (Menu body)

### Do you want to contribute this feature and create a pull request

Yes

**Comment by Brisklemonade** [comment]
We have plans to make a custom control option for the Menu. We've figured out how we're going to approach it. The reason it hasn't been done yet is because a control needs certain attributes and event handlers to work and be accessible. We want this behavior to be automatic (like Group, MediaQuery, etc.). If you would like to contribute I can tell you the approach we want to take and you can implement it, or I can get to it!

**Comment by smartgoo** [comment]
Ah makes sense, seems like a much more robust approach! I'd love to contribute, but not 100% confident in my skillset to implement. A couple slots, sure! Something more involved, not sure I can do it as cleanly/concisely as the current contributors can.

**Comment by Brisklemonade** [comment]
Custom Menu control is now available with new update!
