### ISSUE TITLE
[Feature Request] possibility to set up button's size by number like it is with radius 

### ISSUE THREAD

**Issue by Pawel193** [svelteuidev/svelteui#164]
### Usage example, including component, action, motion, or utility API

`
<Button size={36)>
 example
</Button>
`

### Possible implementation - describe how the feature can be implemented

I guess there is no sense to describe implementation way, when it is working in the same method in another components, generaly in some cases it would be even possible to replace such button by other component which allows us to feel more free while setting up (well, actually the one which comes to my mind is ThemeIcon and it rather isn't something which should be used as a button in most situations) it's size, but probably it is no such a big deal to implement it, for somebody who is more into styling and it could be useful for users

### Do you want to contribute this feature and create a pull request

No

**Comment by BeeMargarida** [comment]
I think this is more of a bug, the size has  a type that supports both the 'sm', 'md', etc type of sizes but also a number, so this behavior should already be working.
Will make a PR with a fix

**Comment by BeeMargarida** [comment]
This can be closed when the next minor is released
