### ISSUE TITLE
View source code and Edit this links are broken

### ISSUE THREAD

**Issue by shinokada** [svelteuidev/svelteui#170]
### Link to the page where something isn't quite right

https://www.svelteui.org/core/menu

### Exact quote of what is wrong

The links to View source code and Edit this are broken.

### Are you willing to create pull request with the fix?

No

**Comment by Brisklemonade** [comment]
OH thank you for pointing that out. The Repo is undergoing big changes, so for the time being those links will be broken.

**Comment by mqus** [comment]
Are those changes still going on? To me the docs locations seems very stable atm.

**Comment by Caladan08** [comment]
Actually this problem is not just with the `<Menu />` component, the same is for every other component in the website. If people wanted to help, this would be a big deterrent, since they would then have to go through the whole repo to find the matching file

**Comment by BeeMargarida** [comment]
Yap, this is already fixed, it has not been deployed yet

**Comment by BeeMargarida** [comment]
Fixed in the new version of docs 0.7.6
