### ISSUE TITLE
[Feature Request] Slider/Range input

### ISSUE THREAD

**Issue by indigo-jay** [svelteuidev/svelteui#174]
### Usage example, including component, action, motion, or utility API

This seems a little obvious, and perhaps I'm completely missing it, but how about a slider or range input, a la: https://svelte.dev/repl/e93d43c42b434e3aa3e2a5815f805c75?version=3.22.3

I'm too new to be contributing honestly - new (to varying degrees) to JavaScript/TypeScript/Svelte/SvelteKit, etc.

### Do you want to contribute this feature and create a pull request

No

**Comment by Brisklemonade** [comment]
A Slider component is on the Roadmap for being built by v0.8.0! Thank you for your suggestion though, and if you want to see what else is is coming; you can look at the roadmap on the bottom of the readme.

**Comment by indigo-jay** [comment]
Great, sorry for missing that. That's probably the last bit that I'll need for a project I'm working on.
