### ISSUE TITLE
Tabs.Tab breaks embedded component functionality.

### ISSUE THREAD

**Issue by indigo-jay** [svelteuidev/svelteui#179]
### What package has an issue

@svelteuidev/core

### A clear and concise description of what the bug is

It's easiest to show a simple example App.svelte file:

```
<script lang='ts'>
	// SvelteUI imports
	import { Button } from '@svelteuidev/core';
	import { Tabs } from '@svelteuidev/core';

	function sayHello() {
		console.log('Hello from App component');
	}
</script>

<Button on:click='{sayHello}'>Outside Tab</Button>
<Tabs>
	<Tabs.Tab label='Some Tab'>
		<Button on:click='{sayHello}'>Inside Tab</Button>
	</Tabs.Tab>
</Tabs>
```

Clicking on the **Outside Tab** button writes to the console, clicking on the **Inside Tab** button does not do anything at all. This is the easiest example of the problem, but it extends well beyond that. If you have a component that's bound to a store that is inside a **Tabs.Tab**, it will not update correctly when the underlying store data changes. I attempted to set up an example in the svelte repl, but it didn't like the @ sign in the import.

### In which browser(s) did the problem occur?

Chrome, Safari, and Firefox

### Steps To Reproduce

Create an App.svelte (not SvelteKit, just plain Svelte), then run and click on the buttons.

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes - I can help test anyway. I'm new enough to JavaScript/TypeScript, Svelte, and SvelteUI that I probably can't track down the issue or solve it.

**Comment by BeeMargarida** [comment]
Hi, thank you for making this issue. We will investigate the bug and possibly fix it next patch

**Comment by indigo-jay** [comment]
Thanks! Any idea when the next patch will drop?

**Comment by Brisklemonade** [comment]
Today!

**Comment by indigo-jay** [comment]
Excellent.
