### ISSUE TITLE
svelte version dependency

### ISSUE THREAD

**Issue by indigo-jay** [svelteuidev/svelteui#186]
### What package has an issue

@svelteuidev/core

### A clear and concise description of what the bug is

I'm not sure if this is a bug or not - the latest dev release seems to explicitly state svelte 3.47.0 as the peer dependency. 3.49.0 is the latest version, so trying to upgrade from a previous version of svelteui where you already have the latest svelte installed causes npm errors and warnings.

### Steps To Reproduce

Install the latest svelteui - you'll get svelte 3.47.0 installed. Then npm install svelte@3.47.0 and you'll get:

```
User> $ npm outdated
Package  Current  Wanted  Latest  Location             Depended by
svelte    3.47.0  3.49.0  3.49.0  node_modules/svelte  svelteui-tab-test
User> $ npm install svelte@3.49.0
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: svelteui-tab-test@0.0.0
npm WARN Found: svelte@3.47.0
npm WARN node_modules/svelte
npm WARN   peer svelte@"^3.44.0" from @sveltejs/vite-plugin-svelte@1.0.1
npm WARN   node_modules/@sveltejs/vite-plugin-svelte
npm WARN     dev @sveltejs/vite-plugin-svelte@"^1.0.1" from the root project
npm WARN   5 more (@svelteuidev/core, svelte-check, svelte-hmr, ...)
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer svelte@"3.47.0" from @svelteuidev/core@0.7.1
npm WARN node_modules/@svelteuidev/core
npm WARN   @svelteuidev/core@"^0.7.1" from the root project

changed 1 package, and audited 96 packages in 325ms

10 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
```
Again, not sure if that's intentional or not. There is a vulnerability in svelte 3.47.0 that should make upgrading desirable.

**Comment by Brisklemonade** [comment]
Hey thanks for bringing that to my attention. There seems to be an issue in our build script that messes up the peerdeps. We will release a new patch.

**Comment by Brisklemonade** [comment]
Fixed in latest patch!
