### ISSUE TITLE
Switch disabled not working

### ISSUE THREAD

**Issue by QVllasa** [svelteuidev/svelteui#189]
### What package has an issue

@svelteuidev/core

### A clear and concise description of what the bug is

When trying to disable the Switch component it does not work. Neither conditionally nor hardcoded. 

### In which browser(s) did the problem occur?

Chrome

### Steps To Reproduce

1. Import Switch component from "@svelteuidev/core".
2. Add `disabled` attribute
3. Try to toggle the switch in browser

### Do you know how to fix the issue

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

**Comment by BeeMargarida** [comment]
Can confirm, definitely a bug. It is also missing dark theme styling. Do you want to contribute with a fix for this, or can I go ahead?

**Comment by QVllasa** [comment]
@BeeMargarida Feel free to fix it!
