### ISSUE TITLE
Build error on TypeScript enabled project

### ISSUE THREAD

**Issue by major-mayer** [svelteuidev/svelteui#193]
### What package has an issue

@svelteuidev/core

### A clear and concise description of what the bug is

Inside `/@svelteuidev/composables/utilities/use-deep-search/use-deep-search.js` a few objects are imported from `./utils` without any `.js` suffix.
This is leading to problems when building a Svelte project using TypeScript, because it is unable to find the utils file.
I guess the compiler just appends a `.ts` suffix in this case and searched for `utils.ts` which doesn't exist, obviously.

This is (also?) happening with SSR enabled.

Replacing `./utils` with `./utils.js` worked for me.

### In which browser(s) did the problem occur?

Firefox, Other - list in description

### Steps To Reproduce

1. Create a SvelteKit project with Typescript enabled
2. Add a basic route like this that is using the SvelteUIProvider
3. Execute `npm run dev`

### Do you know how to fix the issue

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

### Relevant Assets

```
Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/path/to/my/repo/node_modules/@svelteuidev/composables/utilities/use-deep-search/utils' imported from /path/to/my/repo/node_modules/@svelteuidev/composables/utilities/use-deep-search/use-deep-search.js
    at new NodeError (node:internal/errors:372:5)
    at finalizeResolution (node:internal/modules/esm/resolve:437:11)
    at moduleResolve (node:internal/modules/esm/resolve:1009:10)
    at defaultResolve (node:internal/modules/esm/resolve:1218:11)
    at ESMLoader.resolve (node:internal/modules/esm/loader:580:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:294:18)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:80:40)
    at link (node:internal/modules/esm/module_job:78:36)
```

**Comment by Brisklemonade** [comment]
Yeah this just came up as an issue. Someone fixed it in (#191) so that will be fixed in the next patch. Thank you for submitting your issue though!

**Comment by major-mayer** [comment]
You're welcome :)

**Comment by don-wang** [comment]
@Brisklemonade 
May I ask when next patch will be released?
