### ISSUE TITLE
Docs refer to SvelteUIProviderConfig type, which doesn't seem to exist

### ISSUE THREAD

**Issue by CodeCooler** [svelteuidev/svelteui#195]
### Link to the page where something isn't quite right

https://www.svelteui.org/theming/svelteui-provider

### Exact quote of what is wrong

You can change the base background-color and color through the config prop:

```
    import type { **SvelteUIProviderConfig** } from '@svelteuidev/core'; // <-- If using typescript you can import the config type
    config = {
        light: { bg: 'White', color: 'Black' },
        dark: { bg: '#1A1B1E', color: '#C1C2C5' }
    };
```

### Further comment

Perhaps I'm not understanding exactly what this code is supposed to accomplish, but I spent way too much time on the first  "Getting Started"  page before giving up and moving on to the next step without ever managing to change the colors of the page with this method.*

I'd like to propose a fix, but at this stage, I'm not familiar enough with the project to know whether this functionality is deprecated, missing or simply not working as documented.

### Are you willing to create pull request with the fix?

Yes, but unable

**Comment by BeeMargarida** [comment]
I believe that documentation is outdated, but @Brisklemonade can confirm.
Thank you for pointing that out, we will fix it for next release.

**Comment by Brisklemonade** [comment]
@CodeCooler 

@BeeMargarida is correct, that page is outdated. Customization and styling at the global level like that is being completely revamped.
