### ISSUE TITLE
problem during runtime

### ISSUE THREAD

**Issue by BahaaElboraey** [svelteuidev/svelteui#199]
### What package has an issue

@svelteuidev/utilities

### A clear and concise description of what the bug is

Cannot find module 'D:\SvelteUI\node_modules\@svelteuidev\composables\utilities\use-deep-search\utils' imported from D:\SvelteUI\node_modules\@svelteuidev\composables\utilities\use-deep-search\use-deep-search.js

### In which browser(s) did the problem occur?

Edge

### Steps To Reproduce

I tried this code which is in the AppShell tutorial

`<script>
	import { fns, AppShell, Navbar, Header, Title, Divider } from '@svelteuidev/core';
let isDark = false;
	let opened = false;
	function toggleTheme() {
		isDark = !isDark;
	}
	function toggleOpened() {
		opened = !opened;
	}
</script>
<AppShell>
	<Navbar slot="navbar" hidden={!opened}>
		</Navbar>
</AppShell>
`

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

No

**Comment by BeeMargarida** [comment]
Hi, this was already solved, missing just the release.
Thank you!

**Comment by Brisklemonade** [comment]
@psycho-baller @BahaaElboraey the issue has been fixed in the latest patch!
