### ISSUE TITLE
Modal attempt: Error with wrapping app in the SvelteUIProvider

### ISSUE THREAD

**Issue by WebShapedBiz** [svelteuidev/svelteui#202]
### What package has an issue

@svelteuidev/core

### A clear and concise description of what the bug is

Hi.
Using SvelteKit 1.0.0-next.445, with the new Routing system, I have this case:
`+layout.svelte` file:
```
<script>
    import { SvelteUIProvider } from '@svelteuidev/core';
    import { page } from '$app/stores';
</script>
...
<div class="container">
    <SvelteUIProvider>
        <slot />
    </SvelteUIProvider>
</div>
```
as per your instructions here: https://www.svelteui.org/theming/svelteui-provider

`+page.svelte` file:
```
<script>
    import { Modal, Button } from '@svelteuidev/core';
    let opened = false;
    import Time from "svelte-time";
    /** @type {import('./$types').PageData} */
    export let data;
</script>
...
<Modal {opened} on:close={() => (opened = false)} overflow="inside">	
	{@html data.content}
</Modal>
<Button on:click={() => (opened = true)}>Dnevni red</Button>
```
as per your docs.

VS Code with the Svelte plugin doesn't report any errors but in the browser console I'm getting this error:
`Error: Wrap your app in the SvelteUIProvider, or provide a sufficent target throught the "target={''}" prop `

Needless to say, the Modal content is never rendered in HTML, only these two lines, one below the other:
```
<!--<Modal>-->
<!--<Error>-->
``` 

Thank you for your time and effort putting SvelteUI together.

Cheers.

### In which browser(s) did the problem occur?

Chrome

### Steps To Reproduce

As mentioned in the description.

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

**Comment by SlappyAUS** [comment]
I am getting the same. Have tried both SvelteUIProvider and the target prop. I am using the App.svelte method.

**Comment by WebShapedBiz** [comment]
Thank you very much @BeeMargarida for your quick response.

**Comment by BeeMargarida** [comment]
You can close after the fix, so that it's clearer that it's not solved yet :smile:

**Comment by WebShapedBiz** [comment]
Oops, my bad.

**Comment by BeeMargarida** [comment]
This should already be resolved in the new release 0.7.5 (an announcement will be made)

**Comment by brooke1220** [comment]
Uncaught (in promise) Error: Wrap your app in the SvelteUIProvider, or provide a sufficent target throught the "target={''}" prop

**Comment by BeeMargarida** [comment]
> Uncaught (in promise) Error: Wrap your app in the SvelteUIProvider, or provide a sufficent target throught the "target={''}" prop

You need to set SvelteUIProvider in your +layout, like it's demonstrated [here in the docs](https://svelteui.dev/theming/svelteui-provider)
