### ISSUE TITLE
NativeSelect placeholder is shown in the menu

### ISSUE THREAD

**Issue by BastelKlug** [svelteuidev/svelteui#204]
### What package has an issue

@svelteuidev/core

### A clear and concise description of what the bug is

You can find the placeholder for the NativeSelect component also in the select menu but it is disabled.
The bug is not reproducible on chrome.

### In which browser(s) did the problem occur?

Safari

### Steps To Reproduce

1. Open https://www.svelteui.org/core/native-select on Safari
2. Click one of the NativeSelect Components with a placeholder

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

No

### Relevant Assets

Safari:
<img width="866" alt="bug" src="https://user-images.githubusercontent.com/44060099/192141559-a9495b22-9db0-4ce3-a2ac-2a9a1dc3ed69.png">

Chrome:
<img width="866" alt="no bug" src="https://user-images.githubusercontent.com/44060099/192141665-22f33d41-75e3-4601-a0d3-2497e54cc827.png">

**Comment by BeeMargarida** [comment]
I don't think there is a bug here, since NativeSelect uses the `<select>` tag, which has different behaviour in each browser. This is just the normal behaviour of `<select>` in Safari.

**Comment by BastelKlug** [comment]
Oh, less work for us 😂 
I did not know it, thank you
