### ISSUE TITLE
[Feature Request] Implement Chips component

### ISSUE THREAD

**Issue by mrbrianevans** [svelteuidev/svelteui#206]
### Usage example, including component, action, motion, or utility API

```svelte
<script>
import { Chip } from '@svelteuidev/core'
</script>

<Chip.Group>
  <Chip>React</Chip>
  <Chip>Angular</Chip>
  <Chip>Vue</Chip>
  <Chip>Svelte</Chip>
</Chip.Group>
```

![image](https://user-images.githubusercontent.com/53117772/193002453-70619435-5c12-4a89-98d1-c9337d0aaf3c.png)

### Possible implementation - describe how the feature can be implemented

A new component needs to be created.

 - must have a group component to contain multiple Chips
 - must have a binding for the current selected chip
 - maybe dispatch an event when selection is changed
 - must support generic props such as disabled and variant

### Do you want to contribute this feature and create a pull request

Yes

**Comment by Brisklemonade** [comment]
I agree with this proposal. Would you like guidance on making a contribution?

**Comment by mrbrianevans** [comment]
Yes please I would like some guidance. I can probably use other components as examples as well.
Also I'm participating in Hacktoberfest, so would like my PR to count for that, if you are willing to label it as hacktoberfest?

**Comment by mrbrianevans** [comment]
I am attempting to implement this, but I need a bit of guidance. 

I've cloned the repo and installed dependencies (`yarn install`), I've swtiched to Node@v16.

When I try running `yarn run dev:core` (in monorepo root) to startup storybook so I can see the new component I'm developing, I get errors in the console and the Storybook UI only shows a loading skeleton.

The console error messages are like this:
```
[vite] Internal server error: Failed to resolve entry for package "@svelteuidev/composables". The package may have incorrect main/module/exports specified in its package.json.
  Plugin: vite:import-analysis
  File: C:/Users/bme/projects/svelteui/packages/svelteui-core/src/components/Portal/Portal.svelte
```
and there is an error for each of these components: `Portal`, `ObserverRender`, `Modal` and `Menu`.

It also gives an error like this 6 times:
```
Failed to resolve entry for package "@svelteuidev/composables". The package may have incorrect main/module/exports specified in its package.json.
```

And also:
```
Story name conflict with exports - Please add an explicit id for story Alert
Story name conflict with exports - Please add an explicit id for story Button
Story name conflict with exports - Please add an explicit id for story Menu
```

Not sure if all of these logs messages are fatal, but the end result is that Storybook isn't working. Do you get these messages when you run it locally? Is there any more setup required than what I described? Any ideas what could solve these problems?

Many thanks for your help!

**Comment by mrbrianevans** [comment]
@Brisklemonade

**Comment by BeeMargarida** [comment]
> I am attempting to implement this, but I need a bit of guidance.
> 
> I've cloned the repo and installed dependencies (`yarn install`), I've swtiched to Node@v16.
> 
> When I run `yarn run dev` in the monorepo root, it starts storybook with these console messages:
> 
> ```
> Story name conflict with exports - Please add an explicit id for story use-debounce
> Story name conflict with exports - Please add an explicit id for story Button
> Story name conflict with exports - Please add an explicit id for story Menu
> Story name conflict with exports - Please add an explicit id for story Month
> ```
> 
> Not sure if thats a problem. But then in storybook UI, its only showing a few components (`Alert`, `Button` and `Menu`). How can I get them all to show up? Particularly the new one I've created `Chip`? Doesn't show in search results. Apart from adding the source code for the component, do I need to add it somewhere else as well to show up in storybook?
> 
> ![image](https://user-images.githubusercontent.com/53117772/193865500-3f285b58-a34b-4150-afc7-2002b3e58c3f.png)
> 
> Many thanks for your help!

Hi! Sorry for the delay in giving you a response. The storybook setup is recent, we still haven't gotten around to implement stories for all the components, it's still WIP. 
That warning messages are not important for now, there's a bug in storybook with defining ids for stories that we are still investigating.
If you make a Chip.stories.svelte (similar to what we already have in Alert.stories.svelte, for example), when running storybook again it should appear (make sure the name of the story is correct)
