### ISSUE TITLE
outdated layout page naming convention

### ISSUE THREAD

**Issue by jNaimXIII** [svelteuidev/svelteui#226]
### Link to the page where something isn't quite right

https://www.svelteui.org/theming/ssr

### Exact quote of what is wrong

It's been a while since SvelteKit moved to the `+layout.svelte` naming convention instead of the old `__layout.svelte`. This should be updated, right?

### Are you willing to create pull request with the fix?

Yes

**Comment by BeeMargarida** [comment]
Thank you for your contribution!!
