### ISSUE TITLE
`Code` component props are not optional

### ISSUE THREAD

**Issue by j-tai** [svelteuidev/svelteui#230]
### What package has an issue

@svelteuidev/core

### A clear and concise description of what the bug is

Many props of the `Code` component are required instead of optional, even though the [documentation](https://www.svelteui.org/core/code) shows that `Code` can be used without any props.

Since they are not optional, this results in type errors for TypeScript users:

```
Error: Type '{}' is not assignable to type 'IntrinsicAttributes & { class?: string | undefined; color: SvelteUIColor; block: boolean; width: number; copy: boolean; message: string; noMono: boolean; ... 17 more ...; pr?: (string & Record<...>) | ... 1 more ... | undefined; }'.
  Type '{}' is missing the following properties from type '{ class?: string | undefined; color: SvelteUIColor; block: boolean; width: number; copy: boolean; message: string; noMono: boolean; className?: string | undefined; override?: CSS | undefined; ... 15 more ...; pr?: (string & Record<...>) | ... 1 more ... | undefined; }': color, block, width, copy, and 2 more. (ts)
```

### Steps To Reproduce

1. Write `<Code>foo</Code>` in a TypeScript project
2. `npm run check`

### Do you know how to fix the issue

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

**Comment by BeeMargarida** [comment]
Sorry, forgot to respond, it is indeed a bug, will be fixed in the next patch (not 0.7.6, since this was released today and I forgot to fix this there 😬 )

**Comment by BeeMargarida** [comment]
Fixed in new release 0.7.7

**Comment by Schmell** [comment]
This appears to be an issue with Image component as well

**Comment by BeeMargarida** [comment]
> This appears to be an issue with Image component as well

Thank you, I'll open a PR tomorrow with a fix
