### ISSUE TITLE
Unable to contribute as running `yarn dev` in docs folder raises errors

### ISSUE THREAD

**Issue by Caladan08** [svelteuidev/svelteui#233]
### What package has an issue

@svelteuidev/core

### A clear and concise description of what the bug is

This is really a problem with the docs folder. I have followed the **How To Contribute** todo list given in `CONTRIBUTING.md` to a T and still this error persists. After running `yarn install` in the root folder (in the `next-minor` branch), I cded into `/apps/docs` and ran `yarn install` again there. After this, I ran `yarn dev` and I got the following error in my console:
```js
[rollup-plugin-svelte] Unknown "dev" option. Please use "compilerOptions" for any Svelte compiler configuration.
[rollup-plugin-svelte] Unknown "dev" option. Please use "compilerOptions" for any Svelte compiler configuration.
rollup v2.79.1
bundles /Users/caladan/Code/svelteui/node_modules/@svelte-docs/core/main.js → __DOCS__/dev/bundle.js...
(!) Config.aliases: No such file
/Users/caladan/Code/svelteui/packages/svelteui-core/package/index.js
```

I tried to run `yarn dev` in the `main` branch as well and in it, the code did execute and generate a localhost server, but nothing appeared on the screen then. The page heading and icon was rendered properly but nothing else. It looked like this:
<img width="1440" alt="Screenshot 2022-11-25 at 10 57 15 PM" src="https://user-images.githubusercontent.com/94300963/204033217-770ea4ba-22bd-4d6d-84dc-186d3ebcfbe0.png">

And in the console of the developer tools, this error pops up:
```js
Uncaught ReferenceError: core is not defined
    at main.js:6:2
```

### In which browser(s) did the problem occur?

Other - list in description

### Steps To Reproduce

1. Clone the repo
2. Run `git checkout next-minor` if you want to see the first error, or stay in the `main` branch if you want to see the second error
3. Run `yarn install` in the root folder
4. cd into the docs by running `cd apps/docs`
5. Run `yarn install` again
6. Run `yarn dev`

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

### Relevant Assets

I mainly use Brave as a browser but the same error was there in Safari as well

**Comment by BeeMargarida** [comment]
The problem is more lack of documentation, I'll add these steps to the CONTRIBUTING guide. To run the docs:

In the root of the project:
* Run `yarn package`
* Run `yarn dev:docs`
* Ignore the logs in the console (the docs use a package that is a bit outdated, we are in the process of working out a better docs solution)

**Comment by Caladan08** [comment]
Thanks! This fixed it
