### ISSUE TITLE
Modal doesn't trap focus so keyboard navigation is not working

### ISSUE THREAD

**Issue by CanRau** [svelteuidev/svelteui#241]
### What package has an issue

@svelteuidev/core

### A clear and concise description of what the bug is

When opening the [Modal](https://www.svelteui.org/core/modal) via keyboard then using tab key to navigate within the just opened modal focus stays on the website behind instead making it basically impossible to keyboard navigate as you'd have to reach the end of the website until focus finally enters the modal

An example of how this should work, just before the linked "Dialog" headline is an `Open Dialog` button, activate it via keyboard or mouse then use tab key to navigate between elements, the focus stays within the modal
https://react-spectrum.adobe.com/react-aria/useModalOverlay.html#dialog

### In which browser(s) did the problem occur?

Firefox

### Steps To Reproduce

1. Go to https://www.svelteui.org/core/modal
2. Open the first Modal example below Usage headline, either via keyboard or mouse
3. press tab key to focus first input element
4. it's focusing behind the modal instead

### Do you know how to fix the issue

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix

No

**Comment by BeeMargarida** [comment]
Thank you for pointing this out! I've opened a PR with a fix
