### ISSUE TITLE
The changelog should sorted in descending

### ISSUE THREAD

**Issue by mazipan** [svelteuidev/svelteui#253]
### Link to the page where something isn't quite right

https://www.svelteui.org/changelog/v0-5-0

### Exact quote of what is wrong

The newest release should be shown in the very top order

<img width="230" alt="Screen Shot 2022-12-22 at 16 44 55" src="https://user-images.githubusercontent.com/7221389/209106234-f5f524a8-1037-44bb-ad5f-e1d20cc57b53.png">

### Are you willing to create pull request with the fix?

No

**Comment by BeeMargarida** [comment]
The docs will be released when the next patch is also released, gonna close this since it was fixed by @Caladan08 🙏!
