### ISSUE TITLE
Anchor component has undocumented required `root` and `external` properties when packaged

### ISSUE THREAD

**Issue by drewbitt** [svelteuidev/svelteui#258]
### What package has an issue

@svelteuidev/core

### A clear and concise description of what the bug is

![image](https://user-images.githubusercontent.com/26885897/209597727-8982dd4a-f96c-4fdb-b6d2-41332f4baf61.png)

Examples, documentation should be updated to reflect this change, or a revertion. Code will work without them set but it will show errors in editors

### Steps To Reproduce

Download 0.7.7 via the npm registry 

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

No

**Comment by BeeMargarida** [comment]
Ah, those should be optional props, I'll fix it and also add a mention of the `external` prop to the docs, for now

**Comment by BeeMargarida** [comment]
Gonna close this since the fix was merged, it will be fixed in the next patch
