### ISSUE TITLE
Cannot set "class" on Title

### ISSUE THREAD

**Issue by drewbitt** [svelteuidev/svelteui#265]
### What package has an issue

@svelteuidev/core

### A clear and concise description of what the bug is

According to the [FAQ](https://www.svelteui.org/faq), in order to integrate with Tailwind you add the "class" property. In the example, the Button class has the property. However, Title does not

![image](https://user-images.githubusercontent.com/26885897/209844164-7d4ae792-5b18-422b-bda5-8f803095c106.png)

Using className is not an alternative as it does not set "class" on the DOM element

### Steps To Reproduce

Download 0.7.7 from the npm registry

### Do you know how to fix the issue

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix

No

**Comment by BeeMargarida** [comment]
It should be fixed now in the next patch (to come)

**Comment by drewbitt** [comment]
It is fixed in the next-minor branch. Thanks @BeeMargarida

**Comment by drewbitt** [comment]
@BeeMargarida this seems to have regressed between your patch and the release of 0.8 as the error has returned

**Comment by BeeMargarida** [comment]
Thank you for pointing it out, will fix it and release a new patch

**Comment by BeeMargarida** [comment]
This should be totally fixed in the new release 0.9.0
