### ISSUE TITLE
Can't use `Tabs` or `Alert` in default SvelteKit project

### ISSUE THREAD

**Issue by Caladan08** [svelteuidev/svelteui#272]
### What package has an issue

@svelteuidev/core

### A clear and concise description of what the bug is

When I use either the `Tabs` or the `Alert` component with an icon in the default SvelteKit application with TypeScript, the following error pops up:
```js
HTMLElement is not defined
```
It seems to be caused by the `IconRenderer.svelte` file having issues when we run the app with SSR.

### In which browser(s) did the problem occur?

Other - list in description

### Steps To Reproduce

Repro: https://github.com/Caladan08/icon-renderer-issue-repro

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

**Comment by Caladan08** [comment]
Oops, I didn't know that this would be fixed in the next patch. Sorry

**Comment by BeeMargarida** [comment]
No problem, the PR should be merged in time for the next patch
