### ISSUE TITLE
NativeSelect on:change event handler is called before value is updated

### ISSUE THREAD

**Issue by vsergeev** [svelteuidev/svelteui#277]
### What package has an issue

@svelteuidev/core

### A clear and concise description of what the bug is

The `on:change` callback with `NativeSelect` is called before the binded value is updated. This differs from how Svelte handles `<select>`.

### In which browser(s) did the problem occur?

Firefox

### Steps To Reproduce

Reproduced here: https://stackblitz.com/edit/vitejs-vite-tfksaq?file=src/App.svelte

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

No

**Comment by BeeMargarida** [comment]
Should be fixed now in the next patch release, thank you for this bug report!

**Comment by vsergeev** [comment]
:+1: thank you!
