### ISSUE TITLE
SSR not working with svelteKit 1.0

### ISSUE THREAD

**Issue by Rick-Young** [svelteuidev/svelteui#285]
### What package has an issue

@svelteuidev/core

### A clear and concise description of what the bug is

I'm starting a new project with svelteKit 1.0 and svelteUI and I'm trying to get ssr working correctly. In my +layout.svelte I import { SvelteUIProvider } from '@svelteuidev/core'; then I'm setting the ssr prop. see below but it does not render any styles on the page for the sevlteui components

<SvelteUIProvider ssr withNormalizeCSS withGlobalStyles themeObserver={isDark ? 'dark' : 'light'}>

    <Header toggleTheme={toggleTheme} />

    <slot></slot>

</SvelteUIProvider>

Also I created a **hooks.server.ts** file at the same level as my +layout.server.ts file will with the following code to see if that would help but it could not find the prepareStylesSSR in the '@svelteuidev/core

import { prepareStylesSSR } from '@svelteuidev/core';

export const handle = prepareStylesSSR;

### Steps To Reproduce

See above

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

No

**Comment by BeeMargarida** [comment]
The latest version `0.8.0` removed the `ssr` prop and introduced the hook solution. Could you please tell me if you are using that version?
Also, the `hooks.server.ts` must be at `src/` level, like it says in the [docs](https://kit.svelte.dev/docs/hooks).

**Comment by Rick-Young** [comment]
Ana,

 

I got it working I had to update to version 0.8.0 and it works now. Thanks for getting back to me so quick

 

Thanks!

 

Rick
