### ISSUE TITLE
Use-css-variable.ts

### ISSUE THREAD

**Issue by mdpotter55** [svelteuidev/svelteui#31]
### What package has an issue

@svelteuidev/actions

### A clear and concise description of what the bug is

Your use-css-variable is an intriguing solution. I like that it doesn't add an artifact like the Svelte solution.  Of course, your solution requires javascript.   

If I am not mistaken, the update(_props) function is missing an assignment after the old prop values are cleaned up - at the end: 
prop = _prop;

Otherwise, the second update would always find the prop object in a useless state (no key/values in use).  

### In which browser(s) did the problem occur?

Chrome

### Do you know how to fix the issue

Yes

**Comment by Brisklemonade** [comment]
Thank you for pointing this out, I didn't even notice that haha. I will fix that asap!

**Comment by Brisklemonade** [comment]
After looking into it, I realized that this isn't actually correct. So I'll be closing this issue now!

**Comment by mdpotter55** [comment]
I am always wary of my coding, but I still see an obscure bug that will
only show itself in edge cases. When new props are updated for the second
time, old CSS properties (ones created during the first update) could
remain in effect when it is not the programmers intention. Perhaps I lack
some knowledge of how the "use:" statement works.

In my mind, a better solution would be the use of a style={$cssPropties}
scheme. It has the added benefit of working with SSR, valid initial
settings when JavaScript is disabled, and of being self-cleaning.

**Comment by Brisklemonade** [comment]
If you can provide an example where those edge cases actually occur then I can dive further into it. Also you should look into actions, they're very useful and self cleaning.

That style syntax looks like you're trying to use a store which doesn't necessarily make sense to me, so could you explain that?

And finally, the use-css-variable action is valid for ssr (no dom api's are being called). You need JavaScript to dynamically change values of css properties, whether you're using the action or not.

**Comment by mdpotter55** [comment]
I don't want to rain on your parade, but actions do not execute in SSR -
they fire after the element is created during hydration on the client. I
just ran a simple test for my sanity. SvelteKit does not execute *use:*
directives in SSR. Disable JS (kills hydration) in any of your samples, and
you will see. It makes sense since HTMLElement (the node parameter) is not
created on the server (and certainly none of its browser-dependent
functionality). I do believe there is a request to have this done without
HTMLElement access, but it's not present in the current version.

I will create a contrived REPL of the edge case tomorrow (I am committed to
a trivia contest tonight). Perhaps, I will be proved wrong, but in any case
I will also show the *store *method. At least with a store, the initial
values are set during SSR as a failsafe. Granted, some simple CSS could set
initial values in any method.

Mike

**Comment by Brisklemonade** [comment]
I guess I misinterpreted what you meant by non ssr compatible. You are correct that the action gets applied when the node enters the dom. If you find that your app needs functionality beyond what an action provides, then you may be able to create a better implementation than I can haha.

I'd love to see your edge case and store example though. So until then I will do some more digging. Good luck with your trivia contest!

**Comment by mdpotter55** [comment]
Here is the REPL
<https://svelte.dev/repl/b194632769004b11a0654ecc5cf38738?version=3.48.0> I
promised.

It is the simplest example I could think of.
cssvar.js is your code (minus the typescript)
csStore.js is a simple user defined store.

[Set One] to set the property object from {} to new values.
[Set Two] to change them again and see the error. (one property not
removed)
The value of the object is listed below the <h1>s.
Uncomment the line in cssvar.js to see the fix work.

The store has the added benefit of working in SSR to set defaults.
I have also used the technique to write complex dynamic CSS in the
<svelte:head> tag.

**Comment by Brisklemonade** [comment]
Wow, that was a simple yet great example. Thank you for not giving up on the issue 😂. I do get the benefit of using a store for this, however I still want to keep the action so it will stay. I may add a section in the docs for how you can ssr with the store if it's demanded enough.

For the fix would you prefer I just do it, or would you like to submit a pr for it?

**Comment by mdpotter55** [comment]
I doubt it will be demanded because most developers don't see the issues.
You should realize the limitations - I added a new component to the REPL
which can't have a use: directive since they can only be placed on DOM
elements. Style attributes can be passed through. It's a design choice and
certainly has no black & white correct answer. I prefer to use actions when
there are no SSR ramifications (i.e. when it is wholly javascript dependent
such as drag & drop).

You can go ahead and fix the issue since my Github skills are limited. One
of these days I'll spend some time correcting that.

**Comment by Brisklemonade** [comment]
Okay sounds good. Also I'd just like to point out that I will be adding a way to pass down actions, and transitions to a component.

**Comment by Brisklemonade** [comment]
Issue has been fixed, closing!
