### ISSUE TITLE
Nested Tabs do not work

### ISSUE THREAD

**Issue by MDesharnaisX** [svelteuidev/svelteui#318]
### What package has an issue

@svelteuidev/core

### A clear and concise description of what the bug is

In my project, I ended up with nested Tabs and they are broken.
I get the following message for chromium: 
DOMException: Failed to execute 'replaceChild' on 'Node': The new child element contains the parent.
And for firefox : 
Uncaught DOMException: Node.replaceChild: The new child is an ancestor of the parent

### In which browser(s) did the problem occur?

Firefox, Chrome

### Steps To Reproduce

        <Tabs.Tab label='Level1'>
            <Tabs>
                <Tabs.Tab label='Level1.1'>

                </Tabs.Tab>
            </Tabs>
        </Tabs.Tab>
    </Tabs>

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

No

**Comment by BeeMargarida** [comment]
This is already solved in version 0.10.0
