### ISSUE TITLE
color="white" or color="black" setting invalid svelteui color var in dark mode

### ISSUE THREAD

**Issue by drewbitt** [svelteuidev/svelteui#319]
### What package has an issue

@svelteuidev/core

### A clear and concise description of what the bug is

I have a 

```
<Title order={2} color="white">Text here</Title>
```

Which is generating in dark mode
```
.dark-theme .svelteui-c-bQvgQt {
    color: var(--svelteui-colors-white600);
}
```

There is no white600; white only has one var, `--svelteui-colors-white`. Svelteui is attempted to dim colors without dim values.

### Steps To Reproduce

Use a svelteui element utilizing the color attribute; specify the svelteui TextColor "white" or "black"

### Do you know how to fix the issue

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix

No

**Comment by BeeMargarida** [comment]
Forgot to link in the commit, but fixed by https://github.com/svelteuidev/svelteui/commit/b9e68b099513849e561db942b396f361e23ea1a9
