### ISSUE TITLE
Code preview failing for Default Theme color example

### ISSUE THREAD

**Issue by siddarthvader** [svelteuidev/svelteui#326]
### Link to the page where something isn't quite right

https://www.svelteui.org/theming/default-theme

### Exact quote of what is wrong

[
![Screenshot 2023-03-02 at 11 18 11 PM](https://user-images.githubusercontent.com/7977737/222510255-500d87f3-71dc-437f-b1a3-54e0aa5942c7.png)
](url)

### Are you willing to create pull request with the fix?

No

**Comment by BeeMargarida** [comment]
Thank you for reporting this bug! Fixed in the latest commits, it will be deployed when the next release comes out
