### ISSUE TITLE
[Feature Request] Allow for iconify icons

### ISSUE THREAD

**Issue by Beiri22** [svelteuidev/svelteui#327]
### Usage example, including component, action, motion, or utility API

Hi. I just wanted to use your Alert component with an icon of the iconify library. You can use the icon as follows:
```svelte
<script lang="ts">
	import Icon from '@iconify/svelte';
	import warningIcon from '@iconify/icons-mdi/warning';
</script>

<Icon icon={warningIcon} />
```

In your example of the Alert-component, you just pass an icon component to the property. I tried similary something like
```svelte
<Alert title="Warnung!" icon={Icon} iconProps={{icon: warningIcon}}></Alert>
```
but it does not show the icon. So maybe I'm doing it wrong, then please help me. If it's not possible, then I'd like to request this as a feature. You should be able to use the icon library of your choice.

### Do you want to contribute this feature and create a pull request

No

**Comment by BeeMargarida** [comment]
Hum, this is expected behavior so I'm marking it as a bug for now.

**Comment by longnguyen2004** [comment]
Same issue as #373

**Comment by BeeMargarida** [comment]
> Same issue as #373

Yap, thank you, it's definitely that, I'll fix it
