### ISSUE TITLE
Keyboard navigation impossible when Tabs are used

### ISSUE THREAD

**Issue by izzy** [svelteuidev/svelteui#333]
### What package has an issue

@svelteuidev/core

### A clear and concise description of what the bug is

I'm having issues with tabs in tabs in terms of keyboard navigation.

It's especially bad with Tabs - the cursor gets stuck on the Tabs and pressing [Tab] or [Shift]+[Tab] while inside a Tab does not move the cursor away from the tabs.

This is easily reproduceable on the Website as well, as it has multiple Tab elements and a few other Tab-selectable elements like links.

### Steps To Reproduce

1. Got to https://www.svelteui.org/core/tabs
2. Press [Tab] until you're in a Tab-group
3. Try to exit the Tab-group with [Tab]/[Shift]+[Tab]

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

No

**Comment by BeeMargarida** [comment]
This fix will be included in the next release
