### ISSUE TITLE
Default theme spacing doesn't work

### ISSUE THREAD

**Issue by notramo** [svelteuidev/svelteui#335]
When using `override={{ padding: '$md' }}`, the element has 0 padding. Could it be the reason that the default theme lacks the `px` unit after the numbers?

**Comment by BeeMargarida** [comment]
We have `$mdPX` that adds the `px` after. Not a clean solution, but it's what we are using when necessary

**Comment by notramo** [comment]
Why is the `px` left out from the default `$md` size?

**Comment by BeeMargarida** [comment]
We sometimes need to do operations on the values, like `theme.space.xs / 2`, so we went with this approach
