### ISSUE TITLE
After last update, the compiler complained about missing radix-icons-svelte

### ISSUE THREAD

**Issue by Beiri22** [svelteuidev/svelteui#342]
### What package has an issue

@svelteuidev/core

### A clear and concise description of what the bug is

Pre-Update: No problem.
Post-Update: Missing radix-icons-svelte used by svelteui
Work-Around: Explicit dependency for radix-icons-svelte

### Steps To Reproduce

Use sveltekit project with svelteui.
run npm build
see log:
```
[vite]: Rollup failed to resolve import "radix-icons-svelte" from "/XXX/node_modules/@svelteuidev/core/components/FileUpload/FileUpload.svelte".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
```

### Do you know how to fix the issue

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

**Comment by BeeMargarida** [comment]
Yap, thank you for reporting this, it's a mistake. I'll release a patch with a fix this week

**Comment by Beiri22** [comment]
Thanks.
