### ISSUE TITLE
Dark theme uses wrong color in inputs

### ISSUE THREAD

**Issue by gabrielnvian** [svelteuidev/svelteui#343]
### What package has an issue

@svelteuidev/core

### A clear and concise description of what the bug is

When using dark theme, TextInput, NativeSelect (all inputs) components have black as default color (font color).

I believe the default color should be white. (As it was in 0.8.0)

### Steps To Reproduce

```
<SvelteUIProvider withGlobalStyles withNormalizeCSS themeObserver="dark">
    <TextInput/>
</SvelteUIProvider>
```

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

No

**Comment by BeeMargarida** [comment]
I'll release a patch with the fix this  week

**Comment by gabrielnvian** [comment]
@BeeMargarida disabled buttons also seem to suffer the same problem: background-color becomes white. Will that be fixed as well?

**Comment by BeeMargarida** [comment]
> disabled buttons also seem to suffer the same problem: background-color becomes white. Will that be fixed as well?

Thank you for pointing that out, it's been fixed!

**Comment by gabrielnvian** [comment]
@BeeMargarida When can we expect this fixes to be rolled out?

**Comment by BeeMargarida** [comment]
Sorry, we want to make a release in addition with the docs port to SK, that part is basically done, so it will be very soon

**Comment by BeeMargarida** [comment]
@gabrielnvian Sorry, we want to make a release in addition with the docs port to SK, that part is basically done, so it will be very soon
