### ISSUE TITLE
Many components are missing catch-all property for `$$restProps`

### ISSUE THREAD

**Issue by longnguyen2004** [svelteuidev/svelteui#350]
### What package has an issue

@svelteuidev/core

### A clear and concise description of what the bug is

I've noticed that many components are using `$$restProps` but doesn't have `[x: string]: unknown` in their prop type, which causes TypeScript to error out. I haven't checked all the components, but `Menu.Item` is one of them, and probably every component in [this commit](https://github.com/svelteuidev/svelteui/commit/9652c59e40645b82ffded5ce73686c2ab11c7bed) as well. I can make a PR that adds them in if you approve.

### Steps To Reproduce

Use `MenuItem`, which is a `Box` under the hood, and pass in something like `href`

### Do you know how to fix the issue

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

### Relevant Assets

![341102479_743692877431801_1853707743389398122_n](https://user-images.githubusercontent.com/15729831/233624985-14e3b71e-c4eb-4433-8eb0-f8adb6bd98c7.png)

**Comment by longnguyen2004** [comment]
Maybe those other components that I've pointed out don't need extra props, but if I want `Menu.Item` to be an anchor, I can't put `href` on there because there's no corresponding property in the type. Setting it to `HTMLButtonElement` doesn't work either, as it essentially forces `Menu.Item` to be a button, which is not what I want.

**Comment by BeeMargarida** [comment]
It's already a button by default (check prop `root`). I've made a commit with a fix for this particular problem. Do you know of other cases where this happens?

**Comment by longnguyen2004** [comment]
`Menu.Item` is the first thing that comes up to me, the others are probably fine, since you're not expected to change the root of them anyway.

**Comment by BeeMargarida** [comment]
Should be fixed then 👍 I'll probably release a patch this week
