### ISSUE TITLE
Missing docs for FileUpload

### ISSUE THREAD

**Issue by notramo** [svelteuidev/svelteui#354]
There is a FileUpload component, but there is no documentation for it on the website.
@mineofcode, could you provide some guidance?

**Comment by BeeMargarida** [comment]
It's not yet finished, there is still some improvements to be made in terms of the icons and styling

**Comment by notramo** [comment]
Maybe it would be worth to add it with a WIP tag, so users of this library could see that it's already in the works.
Also, we need this widget for a MVP, style is not a problem yet, if functionality is OK.

**Comment by BeeMargarida** [comment]
We will work on it! If you want, you can already use it in the latest version, and there's examples of usage in the storybook: https://github.com/svelteuidev/svelteui/blob/main/packages/svelteui-core/src/components/FileUpload/FileUpload.stories.svelte
