### ISSUE TITLE
[Feature Request] Add `type` parameter for `<Button>`

### ISSUE THREAD

**Issue by notramo** [svelteuidev/svelteui#371]
### Usage example, including component, action, motion, or utility API

`<Button type="submit">Submit</Button>`

### Do you want to contribute this feature and create a pull request

Yes

**Comment by BeeMargarida** [comment]
Hey, this should already be possible, since all parameters of the DOM `<button>` are supported and passed to the component below.
Is this not working for you?

**Comment by BeeMargarida** [comment]
A wild bug has appeared ❗ 🐛 I'll investigate this, thank you for reporting it!

**Comment by notramo** [comment]
It appears with other elements, e.g. `<TextInput type="password" name="user:password"/>` also results in TS error, for both `type` and `name`. (At least `TextInput` has a workaround with `wrapperProps`, but it's not documented.)

**Comment by BeeMargarida** [comment]
Are you using the latest version 0.11.1?

**Comment by BeeMargarida** [comment]
Nice!
