### ISSUE TITLE
Checkbox component does not make use of color prop

### ISSUE THREAD

**Issue by gabrielnvian** [svelteuidev/svelteui#377]
### What package has an issue

@svelteuidev/core

### A clear and concise description of what the bug is

The checkbox component appears gray no matter what color is specified

### In which browser(s) did the problem occur?

Microsoft Edge

### Steps To Reproduce

```
<Checkbox color="blue" size="lg">
	<Icon />
</Checkbox>
```

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

No

**Comment by BeeMargarida** [comment]
Fixed in the new patch 0.12.1
