### ISSUE TITLE
`NativeSelect` text color is not respecting dark theme

### ISSUE THREAD

**Issue by notramo** [svelteuidev/svelteui#382]
### What package has an issue

@svelteuidev/core

### A clear and concise description of what the bug is

![image](https://github.com/svelteuidev/svelteui/assets/26059643/73fc703a-5e5e-417a-bc74-0678a8c429cb)

### Steps To Reproduce

Add a `NativeSelect` widget with the default dark theme.

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

**Comment by BeeMargarida** [comment]
This is already fixed, not yet released
