### ISSUE TITLE
`Button` theme is messed up since 0.12.0

### ISSUE THREAD

**Issue by notramo** [svelteuidev/svelteui#383]
### What package has an issue

@svelteuidev/core

### A clear and concise description of what the bug is

- The text is bold, but it wasn't until 0.12.0.
- Dark theme hover color is the same as light theme. 

### Steps To Reproduce

Use dark theme with `@svelteuidev/core` version ^0.12.0. It occurs in 0.12.1 too.

**Comment by BeeMargarida** [comment]
> The text is bold, but it wasn't until 0.12.0.

This was a bug, since the default text should have been bold all along

> Dark theme hover color is the same as light theme.

I don't understand, what's really the problem? Can you provide a screenshot/video?

**Comment by BeeMargarida** [comment]
Ah, oki, the problems are for the variants `subtle`, `default` and `outline`. I'll fix this today

**Comment by BeeMargarida** [comment]
I'll make a release next week with these fixes. I'll be away from the computer for a few days and due to the recent migration to @sveltejs/package 2, there might be some problems when a new release is made, so I would like to be totally available to fix them if they do appear.

**Comment by BeeMargarida** [comment]
Fixed in new release 0.13.0
