### ISSUE TITLE
`ActionIcon` not respecting dark theme since 0.12.0

### ISSUE THREAD

**Issue by notramo** [svelteuidev/svelteui#384]
### What package has an issue

@svelteuidev/core

### A clear and concise description of what the bug is

`ActionIcon` component uses the same colors with dark theme as the light theme.
Tested variants: `filled` (looks bad), `default` (looks terrible), `outline` (kind of OK).

### Steps To Reproduce

Use dark theme with SvelteUI 0.12.0 or 0.12.1.

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

No

**Comment by BeeMargarida** [comment]
Can you include screenshots/videos?

**Comment by notramo** [comment]
![image](https://github.com/svelteuidev/svelteui/assets/26059643/c5271d19-67a0-4acf-8ffb-aba33cc9af7e)

**Comment by notramo** [comment]
For comparison, here is the previous version (0.11.1) of the same ActionIcon:
![image](https://github.com/svelteuidev/svelteui/assets/26059643/736f80b0-49b7-4824-a4ca-97764a96bdbf)

**Comment by BeeMargarida** [comment]
Got it, it's definitely a regression. I think I know what caused it, will fix it today as well

**Comment by BeeMargarida** [comment]
Also fixed by https://github.com/svelteuidev/svelteui/commit/8fd0155dd44b0f9aa964d5e05cf37cab5d761d52

**Comment by BeeMargarida** [comment]
Fixed in new release 0.13.0
