### ISSUE TITLE
Links back to doc github pages via "Edit this page" links not working.

### ISSUE THREAD

**Issue by KevinHodder** [svelteuidev/svelteui#386]
### What package has an issue

@svelteuidev/core

### A clear and concise description of what the bug is

From any given component documentation page, the "Edit this page" github link is broken, because of the move to sveltekit +page.md format

### Steps To Reproduce

1. Go to any given doc page e.g. [this one](https://www.svelteui.org/core/radio)
2. In the header, click "Edit this page"
3. Observe the 404

### Do you know how to fix the issue

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

### Relevant Assets

The whole set of docs can be fixed with a regex replace, and one small string change.

replace `docs: '(\w*)/([\w-]*).md'`
with `docs: '$1/$2/+page.md'`

and update /apps/docs/src/lib/components/Heading.svelte #line 11 
with
		`docs: 'https://github.com/svelteuidev/svelteui/blob/main/apps/docs/src/routes/',`

Tested and confirmed working with these two changes. Tried to push a branch for your consideration, but permission denied.

**Comment by BeeMargarida** [comment]
Thank you for pointing this out :raised_hands:, it has been fixed and deployed
