### ISSUE TITLE
`NumberInput` doesn't fire `on:focus`, `on:blur` and `on:input`

### ISSUE THREAD

**Issue by notramo** [svelteuidev/svelteui#393]
### What package has an issue

@svelteuidev/core

### A clear and concise description of what the bug is

It makes impossible to use with form validation libraries. Currently the only way to get notified of value change is the `on:change` event, but this is not sufficient.

### Steps To Reproduce

Bind event handlers to NumberInput

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

No

**Comment by BeeMargarida** [comment]
Hey, thank you so much for these bug reports! :raised_hands: I really appreciate you taking the time to report them and help us make the library more bug free and useful!
