### ISSUE TITLE
Installation tab is blank

### ISSUE THREAD

**Issue by notramo** [svelteuidev/svelteui#416]
### Link to the page where something isn't quite right

https://www.svelteui.org/installation

### Exact quote of what is wrong

![image](https://github.com/svelteuidev/svelteui/assets/26059643/dabdf96d-72e5-47f9-8439-09643b9e6b33)

**Comment by BeeMargarida** [comment]
Thank you for reporting this, I'll fix this today!

**Comment by BeeMargarida** [comment]
It's fixed, closing
