### ISSUE TITLE
[Improvement] modal transition

### ISSUE THREAD

**Issue by twoco** [svelteuidev/svelteui#430]
It would be great if we could define custom transition for e.g. modals. In best case with global configuration. But let me explain why I created this issue:

The current transition looks a bit rough. Because the scale from 0 to 1. I would start from 0.5 or 0.9.

You could also just set the `start` option for the [scale](https://svelte.dev/docs/svelte-transition#scale). With the change I would not really need a custom transition.

Here is my suggestion. You can play with the values if you like. Maybe this is matter of taste. Just try it out.

```svelte
<div 
  class={classes.transition} 
  transition:scale={{ duration: 200, easing: cubicOut, start: 0.9 }}
>
  ...
</div>
```

[docs](https://www.svelteui.org/core/modal) | [source](https://github.com/svelteuidev/svelteui/blob/718a1f9ca7d92742bb309fbba46fdf7d72b2493e/packages/svelteui-core/src/components/Modal/Modal.svelte#L112C64-L112C64)

**Comment by BeeMargarida** [comment]
I think this can be improved by adding a prop for the transition options, so that there's more control about it.
