### ISSUE TITLE
Collapse animation not working

### ISSUE THREAD

**Issue by BeeMargarida** [svelteuidev/svelteui#437]
### What package has an issue

@svelteuidev/core

### A clear and concise description of what the bug is

Using the example in the Collapse docs in a Svelte app, the animation does not run, the text just appears.

### Steps To Reproduce

1. Create a new svelte app (or use an existing one)
2. Paste the code below
3. Watch it not work

```svelte
<script>
  import { Button, Collapse } from "@svelteuidev/core";

  let open = false;
</script>

<Button on:click={() => (open = !open)}>Open</Button>
<Collapse {open}>
  Avatar: The Last Airbender, also known as Avatar: The Legend of Aang in some
  PAL regions, is an Emmy award-winning American animated television series that
  aired for three seasons on Nickelodeon and the Nicktoons Network. The series
  was created and produced by Michael Dante DiMartino and Bryan Konietzko, who
  served as executive producers along with Aaron Ehasz.
</Collapse>

```

### Do you know how to fix the issue

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

### Relevant Assets

https://github.com/svelteuidev/svelteui/assets/25725586/4b7543ae-465f-4e3e-8711-3532cb2fda46

**Comment by xr0master** [comment]
Since the Accordion also does not work because of this, it will be great to have some kind of hotfix.

**Comment by BeeMargarida** [comment]
Fixed with commit https://github.com/svelteuidev/svelteui/commit/abd13416412c84d4d5429f1de599e69faaa4abe3
