### ISSUE TITLE
How to change font-family globally?

### ISSUE THREAD

**Issue by DoctorRyner** [svelteuidev/svelteui#443]
### What package has an issue

@svelteuidev/core

### A clear and concise description of what the bug is

I change font like this:
```
<SvelteUIProvider
	{themeObserver}
	withGlobalStyles
	override={{
		fontFamily: '"komet"',

	}}
>
	<slot />
</SvelteUIProvider>
```

But it only changes for usual html tags and doesn't work on Text, Title, etc components from @svelteuidev/core

### Steps To Reproduce

Specify font in SvelteUIProvider

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

No

**Comment by BeeMargarida** [comment]
Something like this should work:

```svelte
<script lang="ts">
	import { createTheme, useSvelteUITheme, SvelteUIProvider } from '@svelteuidev/core';

        const newTheme = createTheme('new-theme', {
            ...useSvelteUITheme(),
            fonts: {
                standard: 'Courier New',
                mono: 'Consolas',
                fallback: 'Segoe UI, system-ui, sans-serif'
            },
        });
</script>

<SvelteUIProvider class={newTheme}>
	<slot />
</SvelteUIProvider>

```

**Comment by DoctorRyner** [comment]
Wow, it works. Thank you. I think this should be added to the documentation.
