### ISSUE TITLE
rightSection not clickable in TextInput

### ISSUE THREAD

**Issue by gabrielnvian** [svelteuidev/svelteui#446]
### What package has an issue

@svelteuidev/core

### A clear and concise description of what the bug is

Since v0.15.0, an ActionIcon inside a TextInput's rightSection is not clickable

### In which browser(s) did the problem occur?

Chrome, Microsoft Edge Beta/Dev/Canary

### Steps To Reproduce

```
<TextInput>
	<svelte:fragment slot="rightSection">
		{#if something}
			<Loader/>
		{:else}
			<ActionIcon>
				<IconRefresh color="DodgerBlue" />
			</ActionIcon>
		{/if}
	</svelte:fragment>
</TextInput>
```

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

No

**Comment by BeeMargarida** [comment]
Should be fixed in the new patch version 0.15.1
