### ISSUE TITLE
Loading button style on dark mode

### ISSUE THREAD

**Issue by ePluvinage** [svelteuidev/svelteui#447]
### What package has an issue

@svelteuidev/core

### A clear and concise description of what the bug is

When a button is in "loading" state and the theme is dark, the button gets lighter, whilst you would expect it to get darker.
How it currently is:
![svelteui](https://github.com/svelteuidev/svelteui/assets/130997433/457f43cc-b57e-498a-af46-fc70a5781277)
How I think it should be:
![mantine](https://github.com/svelteuidev/svelteui/assets/130997433/933b4e37-0e7b-4786-921e-58b660c18398)

### In which browser(s) did the problem occur?

Firefox

### Steps To Reproduce

1. Create a loading button with dark theme

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

No

**Comment by BeeMargarida** [comment]
Fixed in latest patch 0.15.2
