### ISSUE TITLE
ActionIcon

### ISSUE THREAD

**Issue by Lakedaemon** [svelteuidev/svelteui#465]
### Link to the page where something isn't quite right

https://www.svelteui.org/core/action-icon

### Exact quote of what is wrong

Colors aren't applied to the icon in the USAGE demo, when variant=defult
(but it works with other variants)

### Are you willing to create pull request with the fix?

Yes

**Comment by BeeMargarida** [comment]
So, the default variant is supposed to not change the color of the icon. The error here is that the "default" value for variant is `hover` and not `default`.
