### ISSUE TITLE
Missing Intellisense when using SvelteUI >= 0.15.0

### ISSUE THREAD

**Issue by BeeMargarida** [svelteuidev/svelteui#470]
### What package has an issue

@svelteuidev/core

### A clear and concise description of what the bug is

Intellisense does not work when using svelteui after 0.15.0. 

### Steps To Reproduce

1. Using VSCode or other editor with a LSP, start a svelte-kit project
2. Install @svelteuidev/core and @svelteuidev/composables  with version 0.15.0
3. Use the code `<Button>Click</Button>`
4. Try to set a prop in button, and notice that the autocomplete does not include any button prop

### Do you know how to fix the issue

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

**Comment by Brisklemonade** [comment]
Why is the intellisense not working?

**Comment by BeeMargarida** [comment]
Oh, forgot to submit the comment explaining, but the .svelte.d.ts os not being generated for some components. A commit that chances the yarn.lock was the one that caused this

**Comment by BeeMargarida** [comment]
Fixed in patch 0.15.4
