### ISSUE TITLE
Please disable auto-collapse for the left navigation accordion on svelteui.org

### ISSUE THREAD

**Issue by boustanihani** [svelteuidev/svelteui#479]
### Exact quote of what is wrong

Please disable auto-collapse for the left navigation accordion on svelteui.org.

This is very distrubing when someone wants to click through all components and explore the toolkit.

### Are you willing to create pull request with the fix?

No

**Comment by Dansvidania** [comment]
@boustanihani found a workaround just opening everything up and only command clicking, that does not collapse the accordions

**Comment by boustanihani** [comment]
Thanks @Dansvidania , I have also been doing this with the "CTRL" button, but I also hope this gets fixed by default :)

**Comment by briannarenni** [comment]
I will say, I just came across the library and this was a bother to me to. Seems small unless you're trying to click through quickly. I'll try @Dansvidania's idea though.

**Comment by BeeMargarida** [comment]
I've pushed a commit to fix this, should be deployed in about half an hour.
Thank you for this feedback 🙌

**Comment by BeeMargarida** [comment]
Fixed and deployed!
