### ISSUE TITLE
Slow UI rendering

### ISSUE THREAD

**Issue by cvelasco88** [svelteuidev/svelteui#482]
### What package has an issue

@svelteuidev/core

### A clear and concise description of what the bug is

I have a simple html on the layout (it can be on the page the same), and during some ms it doesn't load the styles, so it glitches the loading of the website

https://youtu.be/ADwgf3reHTE

### Steps To Reproduce

Make a simple html
Use the Svelte UI Beta components (Button for example)
refresh the website

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

No

### Relevant Assets

https://youtu.be/ADwgf3reHTE

**Comment by cvelasco88** [comment]
> ### What package has an issue
> @svelteuidev/core
> 
> ### A clear and concise description of what the bug is
> I have a simple html on the layout (it can be on the page the same), and during some ms it doesn't load the styles, so it glitches the loading of the website
> 
> https://youtu.be/ADwgf3reHTE
> 
> ### In which browser(s) did the problem occur?
> _No response_
> 
> ### Steps To Reproduce
> Make a simple html Use the Svelte UI Beta components (Button for example) refresh the website
> 
> ### Do you know how to fix the issue
> No
> 
> ### Are you willing to participate in fixing this issue and create a pull request with the fix
> No
> 
> ### Relevant Assets
> https://youtu.be/ADwgf3reHTE

I've been checking the issue deeper. Maybe is related to Vite
https://github.com/vitejs/vite/issues/7608

My impression is that it's related to this late styles update. Maybe you can investigate more about
![image](https://github.com/svelteuidev/svelteui/assets/2356962/44a94f2a-c750-42c8-991a-94ea15730c28)

**Comment by BeeMargarida** [comment]
This is related to the SSR setup we have, see [here](https://www.svelteui.org/theming/ssr). Basically we need to inject our CSS when the page is being built and not only when it's passed to the client
