### ISSUE TITLE
use-id description is incorrect

### ISSUE THREAD

**Issue by sillvva** [svelteuidev/svelteui#486]
### Link to the page where something isn't quite right

https://www.svelteui.org/composables/use-id

### Exact quote of what is wrong

The description for `use-id` is the same as `use-element-size`

> Get element width and height and subscribe to changes

Propose changing it to the following, based on `use-hash`

> Util generates a random UUID

### Are you willing to create pull request with the fix?

No

**Comment by BeeMargarida** [comment]
Thank you for creating the bug report :raised_hands: It has been fixed and deployed
