### ISSUE TITLE
The website is down

### ISSUE THREAD

**Issue by fryezz** [svelteuidev/svelteui#489]
### Exact quote of what is wrong

It is not working, and it can be related to expired domain name,

`C:\temp>curl https://svelteui.org
curl: (35) schannel: failed to receive handshake, SSL/TLS connection failed

C:\temp>curl http://svelteui.org
<HTML><HEAD><meta http-equiv="content-type" content="text/html;charset=utf-8">
<TITLE>302 Moved</TITLE></HEAD><BODY>
<H1>302 Moved</H1>
The document has moved
<A HREF="http://domain-registrar.storage.googleapis.com/expired.html?svelteui.org">here</A>.
</BODY></HTML>`

### Are you willing to create pull request with the fix?

No

**Comment by BeeMargarida** [comment]
Yap, we are checking this out, thanks for pointing it out!

**Comment by fryezz** [comment]
it is working now thanks

**Comment by BeeMargarida** [comment]
Forgot to update this issue, but yep, we changed the domain, it's now https://svelteui.dev/
