### ISSUE TITLE
Required property is not working with Checkbox

### ISSUE THREAD

**Issue by roxaneletourneau** [svelteuidev/svelteui#492]
### What package has an issue

@svelteuidev/core

### A clear and concise description of what the bug is

Checkbox does not pass down the required attribute to the <input /> in the DOM.

### In which browser(s) did the problem occur?

Chrome

### Steps To Reproduce

1. Create a form with a Checkbox having the required prop.
2. The form can be submitted even if the Checkbox is not checked.

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

No

**Comment by BeeMargarida** [comment]
I'll make a patch release this week to fix this, thank you for creating this bug report! :raised_hands:
