### ISSUE TITLE
[Feature Request] Table

### ISSUE THREAD

**Issue by michalss** [svelteuidev/svelteui#499]
### Usage example, including component, action, motion, or utility API

Hi there is not any table component ?

### Do you want to contribute this feature and create a pull request

Yes

**Comment by BeeMargarida** [comment]
Hey, there's a first draft of it, but right now we stopped all new features development to focus on migrating the library to svelte 5, see [here](https://github.com/svelteuidev/svelteui/issues/491)

**Comment by BeeMargarida** [comment]
Also duplicate of https://github.com/svelteuidev/svelteui/issues/406
