### ISSUE TITLE
Header width seems too wide with 100vw

### ISSUE THREAD

**Issue by liuyiqi1999** [svelteuidev/svelteui#67]
### Link to the page where something isn't quite right

https://www.svelteui.org/core/

### Exact quote of what is wrong

The header uses a 'width: 100vw' for width, which ends up with too wide than the html itself, and the github icon looks out of screen when there's a scroll bar or some margin. 
<img width="430" alt="image" src="https://user-images.githubusercontent.com/42669906/168810016-38cdd6a1-24d7-4562-9d0d-1b8ce6e31d2d.png">
I'm not sure why it is set to '100vw', and wondering if it can be 'width: 100%' or something else.

**Comment by liuyiqi1999** [comment]
Cool

**Comment by Brisklemonade** [comment]
Thank you for submitting your issue, closing it now!
