### ISSUE TITLE
Broken link in the Introduction page

### ISSUE THREAD

**Issue by Josiechat** [svelteuidev/svelteui#85]
### Link to the page where something isn't quite right

https://www.svelteui.org/introduction

### Exact quote of what is wrong
I found 2 broken links in the doc :

1. First broken link
Introduction > Package Section > Last item in the list ( svelteui/prism)

Actual link: https://www.svelteui.org/others/prism.md
Suggestion : https://www.svelteui.org/others/prism

2. Second broken link
FAQ > Can I use other css-in-js libraries or SCSS/SASS with SvelteUI?> last link in the paragraph (builtin solution).

Actual link: https://www.svelteui.org/theming/create-styles.md
Suggestion https://www.svelteui.org/theming/create-styles

### Are you willing to create pull request with the fix?

No

**Comment by Brisklemonade** [comment]
Thank you for pointing this out!

**Comment by Josiechat** [comment]
You're welcome! I will add in the description another broken link that i just found.

**Comment by Brisklemonade** [comment]
Okay thank you for finding these issues! The next minor version of SvelteUI is coming Friday, so these changes will be reflected then.

I will leave this issue open until that point, just incase any more incorrect links are found as well.

**Comment by Brisklemonade** [comment]
Fixed the links, closing this issue!
