### ISSUE TITLE
[bug] Contributing page is wider than the viewport on mobile

### ISSUE THREAD

**Issue by khaki32** [svelteuidev/svelteui#92]
### Link to the page where something isn't quite right

https://www.svelteui.org/contributing

### Exact quote of what is wrong

On mobile, the page is wider than the viewport. It's not a breaking problem, but it's jarring. It's caused by long inline code under the "Examples" section that don't get wrapped on container overflow.

To reproduce, open the page through Chrome DevTools, and use the Device Toolbar to switch to a mobile view. The bug should be seen on all phones, but it may not be seen on phones with a large resolution.

### Are you willing to create pull request with the fix?

Yes

**Comment by BeeMargarida** [comment]
Nice catch! :eyes:

**Comment by Brisklemonade** [comment]
fixed!
