### ISSUE TITLE
[Feature Request] Migrate all code demos to the new demos API

### ISSUE THREAD

**Issue by Brisklemonade** [svelteuidev/svelteui#97]
The docs currently have a mix of old demos and new demos. The old demos need to be converted into the new ones.

**Comment by Brisklemonade** [comment]
@BeeMargarida progress on this?

**Comment by BeeMargarida** [comment]
> @BeeMargarida progress on this?

On it, still not finished!

**Comment by Brisklemonade** [comment]
@BeeMargarida has migrated all of the core demos, and I will finish the composables soon.
